name: Sync Latest Release to Main

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  sync-latest-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get latest release info
        id: get_latest_release
        run: |
          LATEST_RELEASE=$(curl --silent "https://api.github.com/repos/${{ github.repository }}/releases/latest" | jq -r .tag_name)
          echo "::set-output name=release_tag::$LATEST_RELEASE"

      - name: Checkout latest release
        run: |
          git fetch origin ${{ steps.get_latest_release.outputs.release_tag }}
          git checkout ${{ steps.get_latest_release.outputs.release_tag }}

      - name: Copy release to main
        run: |
          git checkout main
          git merge ${{ steps.get_latest_release.outputs.release_tag }} --no-commit --no-ff
          git add .
          git commit -m "Updated main with latest release ${{ steps.get_latest_release.outputs.release_tag }}"

      - name: Push to main
        run: git push origin main
        
